---
name: Publish
on: workflow_dispatch
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
    - name: Download content
      run: |
        curl --silent https://content-publisher.herokuapp.com/api/content | tee content.json

